# Generated by Django 2.2.6 on 2019-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statictiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='page',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
