# Generated by Django 2.2.5 on 2019-09-30 15:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('content', tinymce.models.HTMLField(verbose_name='content')),
                ('open_hour', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('yoe', models.IntegerField()),
                ('menu', models.IntegerField()),
                ('satff', models.IntegerField()),
                ('happy_customer', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AboutConfig',
                'verbose_name_plural': 'AboutConfigs',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='home/insta')),
                ('image2', models.ImageField(upload_to='home/insta')),
                ('image3', models.ImageField(upload_to='home/insta')),
                ('image4', models.ImageField(upload_to='home/insta')),
                ('image5', models.ImageField(upload_to='home/insta')),
                ('image6', models.ImageField(upload_to='home/insta')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagrams',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FB', 'facebook'), ('TW', 'twitter'), ('INS', 'instagram'), ('GOO', 'google')], max_length=100)),
                ('lien', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='testimonial')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Temoin',
                'verbose_name_plural': 'Temoins',
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.CharField(max_length=50)),
                ('end_hour', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_working', to='configuration.Day')),
            ],
            options={
                'verbose_name': 'WorkingHour',
                'verbose_name_plural': 'WorkingHours',
            },
        ),
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('icone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_service', to='configuration.Icon')),
            ],
            options={
                'verbose_name': 'ServiceConfig',
                'verbose_name_plural': 'ServiceConfigs',
            },
        ),
        migrations.CreateModel(
            name='MainConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=50)),
                ('text3', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='home/')),
                ('image2', models.ImageField(upload_to='home/')),
                ('image3', models.ImageField(upload_to='home/')),
                ('scroll_image', models.ImageField(upload_to='home/')),
                ('tel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('instagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insta_config', to='configuration.Instagram')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_config', to='configuration.Social')),
                ('working_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_config', to='configuration.WorkingHour')),
            ],
            options={
                'verbose_name': 'MainConfig',
                'verbose_name_plural': 'MainConfigs',
            },
        ),
    ]
