# Generated by Django 2.2.5 on 2019-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_blogconfig_contactconfig_menuconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainconfig',
            name='social',
        ),
        migrations.AddField(
            model_name='mainconfig',
            name='social',
            field=models.ManyToManyField(null=True, related_name='social_config', to='configuration.Social'),
        ),
        migrations.RemoveField(
            model_name='mainconfig',
            name='working_hour',
        ),
        migrations.AddField(
            model_name='mainconfig',
            name='working_hour',
            field=models.ManyToManyField(null=True, related_name='working_config', to='configuration.WorkingHour'),
        ),
    ]
