# Generated by Django 2.2.5 on 2019-10-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20191001_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainconfig',
            name='social',
            field=models.ManyToManyField(related_name='social_config', to='configuration.Social'),
        ),
        migrations.AlterField(
            model_name='mainconfig',
            name='working_hour',
            field=models.ManyToManyField(related_name='working_config', to='configuration.WorkingHour'),
        ),
    ]
