# Generated by Django 2.2.5 on 2019-10-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20191001_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutconfig',
            name='image1',
            field=models.ImageField(null=True, upload_to='about/config'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='image2',
            field=models.ImageField(null=True, upload_to='about/config'),
        ),
    ]
