# Generated by Django 2.2.5 on 2019-10-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_acceuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to='blog/comment'),
        ),
    ]
