# Generated by Django 2.2.5 on 2019-10-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20191001_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='user',
        ),
        migrations.AddField(
            model_name='chef',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
